"""The High Country cast. Palettes start from each NPC's in-game `look`
(src/main.js), lifted ~1.3x because those values were tuned for flat-shaded
procedural figures, not PBR albedo.
"""

OUT = "/Users/brian/Projects/high-country/public/models/chars"


def hexrgb(h, k=1.3):
    return tuple(min(255, int(((h >> s) & 255) * k)) for s in (16, 8, 0))


NO_GUN = {"gunbelt": False, "badge": False, "chain": False, "spurs": False}

CHARS = {
    "harlan": {
        "age": 58, "crown": 1.80, "width": 1.04, "belly": 0.012, "jaw": 1.05, "face": {"nose": 1.1},
        "skin": (146, 104, 84),
        "hair": {"style": "short", "color": (70, 60, 52), "grey": 0.7},
        "facial": {"style": "beard"},
        "hat": {"style": "cattleman", "color": hexrgb(0x3d2918), "band": (34, 26, 20)},
        "top": {"style": "shirt", "color": hexrgb(0x5b3a24), "sleeves": "long"},
        "vest": {"color": hexrgb(0x3a2415)},
        "bottom": {"style": "trousers", "color": hexrgb(0x2a2018, 1.45)},
        "boots": {"style": "western", "color": (60, 38, 24)},
        "bandana": {"color": (96, 40, 32)},
        "gunbelt": True, "badge": False, "chain": False, "spurs": True,
        "walk": {"period": 0.96, "step": 0.56, "arm_swing": 15, "drop": (23, 19)},
    },
    "nell": {
        "sex": "f", "age": 52, "crown": 1.63, "width": 0.97, "hips": 0.02,
        "skin": (160, 120, 100),
        "hair": {"style": "bun", "color": (58, 36, 24), "grey": 0.25},
        "facial": {"style": "none"},
        "hat": {"style": "none"},
        "top": {"style": "blouse", "color": hexrgb(0x7a3b1e), "sleeves": "rolled"},
        "vest": None,
        "bottom": {"style": "skirt", "color": hexrgb(0x4a3a2c)},
        "boots": {"style": "shoe", "color": (50, 36, 26)},
        "apron": {"color": (176, 164, 140), "bib": True, "hem": 0.32},
        "bandana": None, **NO_GUN,
        "walk": {"period": 0.9, "step": 0.46, "arm_swing": 12, "drop": (21, 21), "sway": 1.4},
    },
    "wade": {
        "age": 26, "crown": 1.84, "width": 0.97, "shoulders": 1.04, "jaw": 1.08, "face": {"nose": 0.95, "lines": 0.15},
        "skin": (156, 114, 92),
        "hair": {"style": "short", "color": (60, 40, 26), "grey": 0.0},
        "facial": {"style": "stubble"},
        "hat": {"style": "flat", "color": hexrgb(0x2e2118, 1.6), "band": (40, 30, 22)},
        "top": {"style": "shirt", "color": hexrgb(0x6a4e32), "sleeves": "rolled"},
        "vest": {"color": hexrgb(0x4a2e18)},
        "bottom": {"style": "trousers", "color": hexrgb(0x33261a, 1.45)},
        "boots": {"style": "western", "color": (72, 46, 28)},
        "bandana": {"color": (44, 56, 78)},
        "gunbelt": True, "badge": False, "chain": False, "spurs": True,
        "walk": {"period": 0.88, "step": 0.62, "arm_swing": 17, "drop": (23, 19)},
    },
    "dutch": {
        "age": 42, "crown": 1.79, "width": 1.12, "shoulders": 1.10, "belly": 0.01, "chest": 0.012, "jaw": 1.1,
        "face": {"nose": 1.15, "nose_w": 1.2, "brow": 1.2},
        "skin": (150, 108, 78),
        "hair": {"style": "short", "color": (40, 32, 26), "grey": 0.2},
        "facial": {"style": "beard"},
        "hat": {"style": "bowler", "color": (44, 34, 28), "band": (26, 20, 16)},
        "top": {"style": "shirt", "color": hexrgb(0x4a3a30, 1.6), "sleeves": "rolled"},
        "vest": None,
        "bottom": {"style": "trousers", "color": hexrgb(0x26201a, 1.6)},
        "boots": {"style": "work", "color": (40, 30, 24)},
        "apron": {"color": (86, 56, 34), "leather": True, "bib": True, "hem": 0.55},
        "bandana": None, **NO_GUN,
        "walk": {"period": 0.98, "step": 0.56, "arm_swing": 14, "drop": (22, 22)},
    },
    "ruth": {
        "sex": "f", "age": 46, "crown": 1.62,
        "skin": (168, 128, 108),
        "hair": {"style": "bun", "color": (110, 62, 34), "grey": 0.15},
        "facial": {"style": "none"},
        "hat": {"style": "none"},
        "top": {"style": "blouse", "color": hexrgb(0x8a5a34), "sleeves": "long", "collar": True},
        "vest": None,
        "bottom": {"style": "skirt", "color": (80, 62, 50)},
        "boots": {"style": "shoe", "color": (40, 30, 24)},
        "apron": {"color": (200, 190, 170), "bib": False, "hem": 0.36},
        "bandana": None, **NO_GUN,
        "walk": {"period": 0.9, "step": 0.46, "arm_swing": 12, "drop": (21, 21), "sway": 1.4},
    },
    "amos": {
        "age": 63, "crown": 1.76, "width": 0.92, "shoulders": 0.96, "face": {"hollow": 1.4, "nose": 1.15},
        "skin": (150, 108, 86),
        "hair": {"style": "short", "color": (80, 70, 60), "grey": 0.8},
        "facial": {"style": "chevron"},
        "hat": {"style": "slouch", "color": hexrgb(0x3a2a1a, 1.6), "band": (40, 30, 22)},
        "top": {"style": "shirt", "color": hexrgb(0x5f4a2e), "sleeves": "long"},
        "vest": {"color": hexrgb(0x3a2c1a, 1.5)},
        "bottom": {"style": "trousers", "color": hexrgb(0x2e2418, 1.5)},
        "boots": {"style": "western", "color": (70, 50, 34)},
        "bandana": {"color": (120, 100, 70)},
        "props": ["rope"],
        "gunbelt": False, "badge": False, "chain": False, "spurs": True,
        "walk": {"period": 1.0, "step": 0.52, "arm_swing": 13, "drop": (22, 22)},
    },
    "floyd": {
        "age": 34, "crown": 1.85, "width": 0.90, "shoulders": 0.95, "face": {"lines": 0.4, "hollow": 0.8},
        "skin": (158, 114, 90),
        "hair": {"style": "short", "color": (72, 52, 34), "grey": 0.0},
        "facial": {"style": "beard"},
        "hat": {"style": "slouch", "color": hexrgb(0x443626, 1.5), "band": (50, 40, 30)},
        "top": {"style": "shirt", "color": hexrgb(0x7a6a50), "sleeves": "long"},
        "vest": {"color": hexrgb(0x4a3a28)},
        "bottom": {"style": "trousers", "color": hexrgb(0x3a3026, 1.4)},
        "boots": {"style": "western", "color": (62, 44, 30)},
        "bandana": {"color": (90, 30, 26)},
        "gunbelt": True, "badge": False, "chain": False, "spurs": False,
        "walk": {"period": 1.06, "step": 0.50, "arm_swing": 10, "drop": (23, 19)},
    },
    "ida": {
        "sex": "f", "age": 58, "crown": 1.64, "width": 1.02, "hips": 0.025, "chest": 0.008,
        "skin": (170, 134, 116),
        "hair": {"style": "bun", "color": (46, 34, 24), "grey": 0.45},
        "facial": {"style": "none"},
        "hat": {"style": "none"},
        "top": {"style": "blouse", "color": hexrgb(0x8a4a3a), "sleeves": "long", "collar": True},
        "vest": None,
        "bottom": {"style": "skirt", "color": (104, 54, 44)},
        "boots": {"style": "shoe", "color": (30, 24, 20)},
        "shawl": {"color": (72, 64, 60)},
        "bandana": None, **NO_GUN,
        "walk": {"period": 0.95, "step": 0.44, "arm_swing": 10, "drop": (20, 20), "sway": 1.3},
    },
    "doc": {
        "age": 64, "crown": 1.74, "width": 1.02, "belly": 0.022,
        "face": {"nose": 1.05, "hollow": 1.1},
        "skin": (168, 124, 104),
        "hair": {"style": "fringe", "color": (138, 132, 120), "grey": 0.9},
        "facial": {"style": "chevron"},
        "hat": {"style": "none"},
        "top": {"style": "shirt", "color": (200, 192, 176), "sleeves": "long", "collar": True},
        "vest": {"color": hexrgb(0x3a342c, 1.5)},
        "coat": {"style": "sack", "color": (70, 62, 54)},
        "bottom": {"style": "trousers", "color": hexrgb(0x2a2620, 1.6)},
        "boots": {"style": "shoe", "color": (30, 24, 20)},
        "props": ["spectacles", "pipe", "cravat"],
        "bandana": None, "gunbelt": False, "badge": False, "chain": True, "spurs": False,
        "walk": {"period": 1.0, "step": 0.50, "arm_swing": 11, "drop": (21, 21)},
    },
    "willie": {
        "age": 11, "crown": 1.36, "head": 1.22, "leg": 0.96, "width": 0.92, "shoulders": 0.9,
        "skin": (176, 136, 110),
        "hair": {"style": "mop", "color": (90, 58, 30), "grey": 0.0},
        "facial": {"style": "none"},
        "hat": {"style": "none"},
        "top": {"style": "shirt", "color": hexrgb(0x6a7a8a), "sleeves": "rolled"},
        "vest": None,
        "suspenders": True,
        "bottom": {"style": "trousers", "color": hexrgb(0x3a342c, 1.5)},
        "boots": {"style": "work", "color": (50, 38, 28)},
        "props": ["satchel"],
        "bandana": None, **NO_GUN,
        "walk": {"period": 0.78, "step": 0.56, "arm_swing": 20, "drop": (22, 22)},
    },
    "hattie": {
        "sex": "f", "age": 36, "crown": 1.60, "width": 0.96,
        "skin": (164, 124, 104),
        "hair": {"style": "bun", "color": (30, 24, 20), "grey": 0.05},
        "facial": {"style": "none"},
        "hat": {"style": "none"},
        "top": {"style": "blouse", "color": hexrgb(0x6a6a7a), "sleeves": "rolled"},
        "vest": None,
        "bottom": {"style": "skirt", "color": (90, 90, 104)},
        "boots": {"style": "shoe", "color": (36, 28, 22)},
        "apron": {"color": (190, 186, 176), "bib": False, "hem": 0.30},
        "bandana": None, **NO_GUN,
        "walk": {"period": 0.88, "step": 0.48, "arm_swing": 13, "drop": (21, 21), "sway": 1.4},
    },
    "cole": {
        "age": 31, "crown": 1.82, "width": 0.95, "jaw": 1.1, "face": {"brow": 1.2, "nose": 1.05, "lines": 0.5},
        "skin": (150, 110, 88),
        "hair": {"style": "short", "color": (40, 30, 24), "grey": 0.0},
        "facial": {"style": "stubble"},
        "hat": {"style": "flat", "color": hexrgb(0x33281c, 1.6), "band": (30, 24, 18)},
        "top": {"style": "shirt", "color": hexrgb(0x554434), "sleeves": "long"},
        "vest": {"color": hexrgb(0x2e241a, 1.5)},
        "coat": {"style": "duster", "color": (118, 98, 74)},
        "bottom": {"style": "trousers", "color": hexrgb(0x30281e, 1.5)},
        "boots": {"style": "western", "color": (48, 34, 24)},
        "bandana": {"color": (50, 40, 36)},
        # His iron rides under the duster; a belt over the coat read as a costume.
        "gunbelt": False, "badge": False, "chain": False, "spurs": True,
        "walk": {"period": 0.94, "step": 0.58, "arm_swing": 12, "drop": (21, 21)},
    },
    "player": {
        "age": 30, "crown": 1.80, "width": 1.0, "jaw": 1.06, "face": {"lines": 0.3},
        "skin": (158, 116, 94),
        "hair": {"style": "short", "color": (64, 44, 30), "grey": 0.0},
        "facial": {"style": "stubble"},
        "hat": {"style": "cattleman", "color": hexrgb(0x3d2918), "band": (34, 26, 20)},
        "top": {"style": "shirt", "color": hexrgb(0x6b4226), "sleeves": "long"},
        "vest": {"color": hexrgb(0x4a2e18)},
        "bottom": {"style": "trousers", "color": hexrgb(0x33261a, 1.45)},
        "boots": {"style": "western", "color": (40, 28, 20)},
        "bandana": {"color": (110, 40, 32)},
        "gunbelt": True, "badge": False, "chain": False, "spurs": True,
        "walk": {"period": 0.92, "step": 0.58, "arm_swing": 16, "drop": (23, 19)},
        "out": "/Users/brian/Projects/high-country/public/models/player.glb",
    },
}

for _id, _spec in CHARS.items():
    _spec["id"] = _id
    _spec.setdefault("out", f"{OUT}/{_id}.glb")
    _spec.setdefault("seed", 1000 + sum(map(ord, _id)))
